### ISSUE TITLE
.

### ISSUE THREAD

**Issue by mcd8604** [Jacotheron/FlashForge-CreatorPro2-PS-Profile#1]

**Comment by mcd8604** [comment]
I started experimenting with slicer settings to see what else might affect this field. It turns out Raft is the third bit:

normal:  00000101
dupe:     00010101
mirror:   00100101

normal_no_raft:  00000001
dupe_no_raft:     00010001
mirror_no_raft:   00100001

![image](https://user-images.githubusercontent.com/2568468/162589759-74c64a0a-dd08-4629-b000-46c52d037d11.png)

**Comment by mcd8604** [comment]
I started a branch to support these findings: 
https://github.com/mcd8604/FlashForge-CreatorPro2-PS-Profile/tree/extruder_mode_fix
TODO list:
- [ ] regex parse for raft_enabled
- [ ] regex parse for supports_enabled

**Comment by Jacotheron** [comment]
Hi @mcd8604
[Simple PLA.txt](https://github.com/Jacotheron/FlashForge-CreatorPro2-PS-Profile/files/8466766/Simple.PLA.txt)

You can see my FlashPrint profile attached here (it is a .fcfg file, that was simply modified to be .txt as it contains text only). I have just sliced a new object with it, and it generated a "19" in duplicate mode.

Ultimately in my various tests, I have not really determined whether this value is even used at all. I simply slice and print - and it comes out great. If you experience a different result, let me know and I can add these extra checks and insert the other values (PS adds them in the comments, so it is as easy as checking for rafts and supports).

One thing I have noticed, is that sometimes the heatup will not block until it is up to temperature, if this happens to you, use the firmware's preheat option, and when up to temperature, select the file for print.

Maybe check what happens to the value when Pre-extrusion, Wall, Brim, Wiping Tower is enabled (also the Ironing and Fuzzy skin).


In my checks I simply generated a bunch of 20x20 cubes and observed the file outputs, and worked until I could convince my printer to actually print it in the way it should. Then I simply made sure the profiles were using sane defaults. I am using the exact same profile now for customer's print on demand work, and it is great for me.

**Comment by mcd8604** [comment]
Thanks for the cfg file!

> You can see my FlashPrint profile attached here (it is a .fcfg file, that was simply modified to be .txt as it contains text only). I have just sliced a new object with it, and it generated a "19" in duplicate mode.

I imported the config and sliced in duplicate mode. However, I am still getting a "17" in the .gx file.

> Ultimately in my various tests, I have not really determined whether this value is even used at all. I simply slice and print - and it comes out great. If you experience a different result, let me know and I can add these extra checks and insert the other values (PS adds them in the comments, so it is as easy as checking for rafts and supports).

I wonder whether these flags even have any impact on the tool pathing from the firmware or if it is just superficial data anyway. Once I get my printer set up, I will print with and without flags and see if I notice any differences.

I've already coded the comment parsing for the Raft and Support flags in another fork (link is above) and could open a Pull Request if you find that it is worth merging (you'll be free to make any changes you want in the PR).

> One thing I have noticed, is that sometimes the heatup will not block until it is up to temperature, if this happens to you, use the firmware's preheat option, and when up to temperature, select the file for print.

That's worrying. Does this happen when slicing with FlashPrint, PrusaSlicer, or both?

> Maybe check what happens to the value when Pre-extrusion, Wall, Brim, Wiping Tower is enabled (also the Ironing and Fuzzy skin).
- Pre-extrusion - no change
- Wall - no change
- Brim - no change
- Wiping Tower - no change
- Ironing - no change
- Fuzzy skin - no change

I've also gone through many more permutations of settings. Out of curiosity, what version of FlashPrint are you running? I wonder if it we have a version difference that might account for the different outputs.

Ultimately, if these fields don't impact the printing process then there's no point in pursuing these details further. I'll post some updates when I get my new machine up and running and try some tests.
