### ISSUE TITLE
Maybe an issue with the latest update

### ISSUE THREAD

**Issue by Xeet04** [Jacotheron/FlashForge-CreatorPro2-PS-Profile#17]
Hi,
First of all thank you for making this preset, I've struggled a lot when i tried doing it myself, but an issue I have encountered is that it gives me a pop-up:
"Preset bundle `FlashForge` version not found in index: 1.0.0"
When I'm done with the installation and it's not showing up in the configuration wizard, is this a known issue or have I done something wrong?

**Comment by fullc360** [comment]
From what I've gathered about the pop-up you can ignore it. Regarding FlashForge not showing in the wizard I figured out that you need to enter `repo_id = non-prusa-fff` under [vendor] (line 3). Please forgive me if this is crappy formatting, literally created an account to pass on this knowledge!

**Comment by Xeet04** [comment]
That seems to have done it, thank you so much, and no worries about any formatting, small issues are better than this not being on the internet.
