### ISSUE TITLE
Post-processing script -- on file -- failed. Error code: 2

### ISSUE THREAD

**Issue by PhytoHacker** [Jacotheron/FlashForge-CreatorPro2-PS-Profile#4]
Jaco, hello.
I am interested in using Prusia slicer together with Flash Forge Creator Pro 2.
Thank you for your work.

I followed your detailed tutorial, but I got the following error at the moment of exporting G-code:
![error ](https://user-images.githubusercontent.com/110792931/183316770-e735e5b6-8509-466c-aa90-ca2df2b4e489.png)
Please advise where the problem could be.

**Comment by Jacotheron** [comment]
Typically an error code of 2 in Python is that the file is not found. The file not being found is the python post processor script. 

I noticed you have double quotes and the "!" in the path, I think this is causing issues. Typically you would use either double quotes or "!" before each space. Change it and see if that solves your issue.
