### ISSUE TITLE
PrusaSlicer has encountered an error

### ISSUE THREAD

**Issue by jjnzprinter** [Jacotheron/FlashForge-CreatorPro2-PS-Profile#5]
I am getting the following error when I attempt to export the g-code

The configured post-processing script does not exist: C:\\Python3.10\\python.exe

I am extremely new at 3D printing and the coding associated with it.  I am guessing I have missed something when installing.  I really can use some help.
Thanks

**Comment by Jacotheron** [comment]
The issue your are experiencing is related to your Python installation. On Windows python typically installs directly on your C drive within a folder named "PythonX.YY" (where X and Y denotes the version you are installing). You should check which version you have.

Then in the vendor/FlashForge.ini file, at line 80 (https://github.com/Jacotheron/FlashForge-CreatorPro2-PS-Profile/blob/a3c78d75dec9868e5f9d0d444d752e78804947a1/vendor/FlashForge.ini#L80) you need to update it to the version/location of your setup (both the python.exe and the post processor should be updated on this line). This should then work (note the use of double slashes).
